import type { Metadata } from "next";
import { Source_Sans_3, Inter } from "next/font/google";
import "./globals.css";

const defaultFont = Source_Sans_3({ subsets: ["latin"], weight: ['700', '600'], style: 'normal', display: 'swap' })

console.log(Object.getOwnPropertyNames(defaultFont));


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={defaultFont.className}>{children}</body>
    </html>
  );
}
